Repository Wedit-project/Client, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat/#5] 폰트 설정, 단위 설정
  Wedit-Client/src/assets/fonts/PretendardVariable.woff2
  Wedit-Client/src/main.jsx
  Wedit-Client/src/pages/HomePage.jsx
  Wedit-Client/src/styles/globalFonts.js
  Wedit-Client/src/styles/globalStyle.js
  Wedit-Client/src/styles/theme.js
Labels: ✨ Feat

#15 [Feat/#10] 메인페이지 기능 미리보기 컴포넌트 구현 / svgr 설치 및 세팅
  Wedit-Client/package.json
  Wedit-Client/src/assets/icons/PreviewIcon1.svg
  Wedit-Client/src/assets/icons/PreviewIcon2.svg
  Wedit-Client/src/assets/icons/PreviewIcon3.svg
  Wedit-Client/src/assets/icons/PreviewIcon4.svg
  Wedit-Client/src/components/mainpage/PreviewBox.jsx
  Wedit-Client/src/pages/HomePage.jsx
  Wedit-Client/vite.config.js
  Wedit-Client/yarn.lock
Labels: ✨ Feat, 🏠 홈페이지

#23 [Feat/#20] 마이페이지 헤더 구현
  Wedit-Client/src/components/mypage/HomeButton.jsx
  Wedit-Client/src/components/mypage/LogoutButton.jsx
  Wedit-Client/src/components/mypage/MyPageHeader.jsx
  Wedit-Client/src/pages/MyPage.jsx
  Wedit-Client/src/styles/globalStyle.js
Labels: ✨ Feat, 👤 마이페이지

#25 [Feat/#21] 마이페이지 ui 구현
  Wedit-Client/src/assets/icons/BigLogo.svg
  Wedit-Client/src/components/mypage/Content.jsx
  Wedit-Client/src/components/mypage/InvitationButton.jsx
  Wedit-Client/src/components/mypage/MakingInvitation.jsx
  Wedit-Client/src/components/mypage/MyPageHeader.jsx
  Wedit-Client/src/components/mypage/MyPageSection.jsx
  Wedit-Client/src/pages/MyPage.jsx
  Wedit-Client/yarn.lock
Labels: ✨ Feat, 👤 마이페이지

#27 [feat/#26] 로그인 페이지 ui 구현
  Wedit-Client/src/assets/icons/LoginLogo.svg
  Wedit-Client/src/assets/icons/loginbackground.svg
  Wedit-Client/src/components/loginpage/Background.jsx
  Wedit-Client/src/components/loginpage/LoginButton.jsx
  Wedit-Client/src/components/mainpage/MainPageFooter.jsx
  Wedit-Client/src/pages/LoginPage.jsx
Labels: ✨ Feat, 🔐로그인페이지

#28 [Feat/#3] 청첩장 페이지 Modal 컴포넌트 구현
  Wedit-Client/index.html
  Wedit-Client/src/assets/img/gallery1.png
  Wedit-Client/src/assets/img/gallery2.png
  Wedit-Client/src/assets/img/gallery3.png
  Wedit-Client/src/assets/img/gallery4.png
  Wedit-Client/src/assets/img/location.png
  Wedit-Client/src/assets/img/tradition.png
  Wedit-Client/src/components/WeddingInvitationPage/congratulatory-money.jsx
  Wedit-Client/src/components/WeddingInvitationPage/gallery.jsx
  Wedit-Client/src/components/WeddingInvitationPage/guest-book-modal.jsx
  Wedit-Client/src/components/WeddingInvitationPage/guest-book.jsx
  Wedit-Client/src/components/WeddingInvitationPage/location.jsx
  Wedit-Client/src/components/WeddingInvitationPage/required-information.jsx
  Wedit-Client/src/components/WeddingInvitationPage/rsvp-modal.jsx
  Wedit-Client/src/components/WeddingInvitationPage/rsvp.jsx
  Wedit-Client/src/pages/WeddingInvitationPage.jsx
Labels: 🎨 Style, 💐 청첩장

#33 [Feat/#30] 컬러코드 세팅
  Wedit-Client/src/components/loginpage/LoginButton.jsx
  Wedit-Client/src/components/mainpage/MainBannerSidebar.jsx
  Wedit-Client/src/components/mainpage/MainBannerSlider.jsx
  Wedit-Client/src/components/mainpage/MainPageFooter.jsx
  Wedit-Client/src/components/mainpage/PreviewInvitationButton.jsx
  Wedit-Client/src/components/mypage/Content.jsx
  Wedit-Client/src/components/mypage/InvitationButton.jsx
  Wedit-Client/src/components/mypage/MakingInvitation.jsx
  Wedit-Client/src/pages/HomePage.jsx
  Wedit-Client/src/styles/theme.js
Labels: ✨ Feat, 🎨 Style

#34 [Feat/#29] 청첩장 페이지 기능 추가
  Wedit-Client/.gitignore
  Wedit-Client/package-lock.json
  Wedit-Client/package.json
  Wedit-Client/src/assets/img/basic.png
  Wedit-Client/src/assets/img/tradition.png
  Wedit-Client/src/components/WeddingInvitationPage/congratulatory-money.jsx
  Wedit-Client/src/components/WeddingInvitationPage/gallery.jsx
  Wedit-Client/src/components/WeddingInvitationPage/guest-book-modal.jsx
  Wedit-Client/src/components/WeddingInvitationPage/guest-book.jsx
  Wedit-Client/src/components/WeddingInvitationPage/location.jsx
  Wedit-Client/src/components/WeddingInvitationPage/required-information.jsx
  Wedit-Client/src/components/WeddingInvitationPage/rsvp.jsx
  Wedit-Client/src/hooks/useKakaoLoader.jsx
  Wedit-Client/src/pages/WeddingInvitationPage.jsx
  Wedit-Client/yarn.lock
Labels: ✨ Feat, 🎨 Style, 💐 청첩장

#36 [Feat/#35] 제작 페이지 테마 선택 Modal 컴포넌트 구현
  Wedit-Client/src/components/editpage/ThemeSelectModal.jsx
  Wedit-Client/src/components/mypage/InvitationButton.jsx
Labels: ✨ Feat, 🎨 Style, ✏️ 제작페이지

#40 [Feat/#39] 홈페이지 청첩장 제작하기 버튼 구현
  Wedit-Client/src/components/mainpage/CreateInvitationButton.jsx
  Wedit-Client/src/components/mainpage/MainPageHeader.jsx
Labels: ✨ Feat, 🏠 홈페이지

#41 [Feat/#31] "사진 선택 페이지 UI, 기능 추가"
  Wedit-Client/package.json
  Wedit-Client/src/App.jsx
  Wedit-Client/src/assets/img/Ellipse14.svg
  Wedit-Client/src/assets/img/photovector1.svg
  Wedit-Client/src/assets/img/photovector2.svg
  Wedit-Client/src/assets/img/photovector3.svg
  Wedit-Client/src/components/PhotoSelectionPage/GalleryPhoto.jsx
  Wedit-Client/src/components/PhotoSelectionPage/PageIndicator.jsx
  Wedit-Client/src/components/PhotoSelectionPage/PhotoSelectionButton.jsx
  Wedit-Client/src/pages/EditPage.jsx
  Wedit-Client/src/pages/GalleryPhotoSelectionPage.jsx
  Wedit-Client/src/pages/MainPhotoSelectionPage.jsx
  Wedit-Client/src/pages/PhotoSelectionPage.jsx
  Wedit-Client/yarn.lock
Labels: ✨ Feat, 🎨 Style, 🖼️ 사진선택페이지

#58 [Feat/#46] 마이페이지 모달 구현
  Wedit-Client/src/assets/icons/close.svg
  Wedit-Client/src/components/mainpage/MainBannerSlider.jsx
  Wedit-Client/src/components/mainpage/MainPageSection.jsx
  Wedit-Client/src/components/mypage/ActionButtons.jsx
  Wedit-Client/src/components/mypage/Content.jsx
  Wedit-Client/src/components/mypage/Invitation.jsx
  Wedit-Client/src/components/mypage/InvitationButton.jsx
  Wedit-Client/src/components/mypage/LinkModal.jsx
  Wedit-Client/src/components/mypage/MakingInvitation.jsx
Labels: ✨ Feat, 👤 마이페이지

#59 [Feat/#47] 배너 스켈레톤 UI 구현
  Wedit-Client/src/components/mainpage/MainBannerSlider.jsx
  Wedit-Client/src/components/mainpage/Skeleton.jsx
Labels: ✨ Feat, 🏠 홈페이지

#62 [Feat/#48] 분석 페이지 UI 구현
  Wedit-Client/src/App.jsx
  Wedit-Client/src/components/analysispage/Header.jsx
  Wedit-Client/src/components/analysispage/ParticipantsSummary.jsx
  Wedit-Client/src/components/analysispage/Section.jsx
  Wedit-Client/src/components/analysispage/VisitorsCount.jsx
  Wedit-Client/src/pages/AnalysisPage.jsx
Labels: ✨ Feat, 🔍분석페이지

#64 [Feat/#63] apiInstance 설정
  Wedit-Client/package.json
  Wedit-Client/src/apis/api/user.js
  Wedit-Client/src/apis/utils/apiIntance.js
  Wedit-Client/yarn.lock
Labels: ✨ Feat, 🔗 API
